<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="cell_base_mass" value="5"/>
  <xacro:property name="cell_base_x_size" value="0.5" />
  <xacro:property name="cell_base_y_size" value="0.5" />
  <xacro:property name="cell_base_z_size" value="0.5" />

  <xacro:macro name="add_cell_base" params="id parent scale name_prefix *origin">
    <link name="${name_prefix}_cell_base_${id}">
      <visual>
        <geometry>
          <mesh filename="file://$(find arm_control)/meshes/cell_base.stl" scale="${scale}"/>
        </geometry>
        <material name="Blue">
          <color rgba="0.3 0.3 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="file://$(find arm_control)/meshes/cell_base.stl" scale="${scale}"/>
        </geometry>
      </collision>

      <inertial>
        <origin rpy="0.0 0.0 0.0" xyz="${cell_base_x_size/2} ${cell_base_y_size/2} ${cell_base_z_size/2}"/>
        <mass value="${cell_base_mass}"/>
        <inertia ixx="1" iyy="1" izz="1" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name_prefix}_cell_base_${id}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name_prefix}_cell_base_${id}"/>
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>

</robot>
