<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="table_mass" value="20.0" />
  <xacro:property name="table_x_size" value="1.0" />
  <xacro:property name="table_y_size" value="0.6" />
  <xacro:property name="table_z_size" value="0.610" />

  <xacro:macro name="add_table" params="id parent scale *origin">
    <link name="table_${id}">
      <visual>
        <geometry>
          <mesh filename="file://$(find arm_control)/meshes/table.stl" scale="${scale} ${scale} ${scale}"/>
        </geometry>
        <material name="Green">
          <color rgba="0.2 1.0 0.2 1.0" />
        </material>

        <collision>
          <geometry>
            <mesh filename="file://$(find arm_control)/meshes/table.stl" scale="${scale} ${scale} ${scale}"/>
          </geometry>
        </collision>
      </visual>

      <inertial>
        <origin rpy="0.0 0.0 0.0" xyz="${table_x_size/2} ${table_y_size/2} ${table_z_size/2}"/>
        <mass value="${table_mass}"/>
        <inertia ixx="1" iyy="1" izz="1" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="table_${id}_joint" type="fixed">
      <parent link="${parent}" />
      <child link="table_${id}" />
      <xacro:insert_block name="origin" />
    </joint>
  </xacro:macro>
</robot>
